### ISSUE TITLE
Request: Filter items and apply settings per filter

### ISSUE THREAD

**Issue by ghost** [Webreaper/QbtManager#4]
This is useful if you use RSS to download different TV-Shows. You could filter a RSS url for specific items, and then apply a different download destination path for all of them. Example:

filter: The.100*
path: /path/to/tv-show

**Comment by Webreaper** [comment]
I don't really want to get into implementing that level of complexity. If people want a full featured RSS client for server-based QBT, then they should request it as a feature in QBT. Alternatively, they should set up Jackett for RSS and use that with Sonarr.

**Comment by ghost** [comment]
Fair enough, thanks anyway!
