### ISSUE TITLE
Qbittorrent 4.4.5 API issue?

### ISSUE THREAD

**Issue by Tailslide** [Webreaper/QbtManager#7]
After installing QBT4.4.5 I started seeing this in my logs:

```
[04:00:06.520--INF] === QbtCleanup Log Started ===
[04:00:07.018--INF] LogLevel: "Information"
[04:00:07.837--INF] Filtered torrents will be deleted with their content.
[04:00:07.837--INF] Signing in to QBittorrent.
[04:00:07.857--INF] No password specified - assuming local auth is disabled in QBT
[04:00:08.885--INF] Exception! The remote server returned an error: (405) Method Not Allowed.
[04:00:08.886--INF] Login failed.
```
If I test the API through python it's working properly.  Anyone else having this issue?

**Comment by Webreaper** [comment]
Did you upgrade to the latest release I created last week to fix this issue?

**Comment by Tailslide** [comment]
Sorry I missed that.. I just upgraded now and strangely it's working for me on windows but not ubuntu. 

I figured out I can test login through bash with this and it's successful:

```
wget --post-data "" http://localhost:8080/api/v2/auth/login
```

I'll keep debugging it might be something specific to my setup.

**Comment by Webreaper** [comment]
Weird. I run it fine on Linux (synology). Is the Linux issue the same, or something else? I did change the build slightly to create a generic Linux exe rather than a ubuntu specific one, so maybe that's it. I'll post a ubuntu targeted build when I get a chance later this morning so you can try that.

**Comment by Tailslide** [comment]
It was my mistake .. my build was failing so my batch file was publishing the old version.  I don't have .net 7 so I just set it back to .net 6 and it seems happy now.  Sorry for the false alarm!

**Comment by Webreaper** [comment]
Nice, thanks!
