### ISSUE TITLE
Max_ratio feature removed

### ISSUE THREAD

**Issue by Tailslide** [Webreaper/QbtManager#8]
Not sure if this was intentional but this commit removed the max_ratio feature:

https://github.com/Webreaper/QbtManager/commit/0d49c192cf6dcb437a598831ae724881b43a43fc

**Comment by Webreaper** [comment]
Oops! I had some local changes and hadn't rebased, so screwed it up. Will get it back in later and do another release (or feel free to revert the removal in a PR if you have time).
